### ISSUE TITLE
有何计划？

### ISSUE THREAD

**Issue by ety001** [ldsn/shortUrl#1]
1、框架？
2、谁来负责？
3、大约多久？

**Comment by yuxuangezhu** [comment]
目前来看,暂时只是为了屯域名....话说还有个.club的域名 挺适合做团队博客的

**Comment by ety001** [comment]
我勒个去。。。搞这么多域名干毛。。。把当前的域名做好就不错了。

我觉得这个域名除了可以用来做短域名外，还可以搞网址导航。把原来的网址导航重新开发下，放到这个域名下面。（这个只是提议）

**Comment by yuxuangezhu** [comment]
网址导航 现在感觉 没啥吸引力 觉得要是开发个我现在用的这种可以自定义的挺好, 链接不用太多 一屏九个左右 简洁 话说 .club的域名还没买呢

**Comment by ety001** [comment]
恩，拨号盘类型的也是可以的。
